# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  lfs: true
  clean: true
- bash: |
   sudo apt install -y openslide-tools python3 python3-openslide
   ls -la .
   python3 deepzoom_tile.py test.svs
  displayName: 'Extract svs'
- task: AzureFileCopy@4
  inputs:
    SourcePath: '*'
    azureSubscription: 'Visual Studio Enterprise(8b90224d-e668-44e0-966d-eaccab1d5e63)'
    Destination: 'AzureBlob'
    storage: 'svsdemo'
    ContainerName: '$web'
