# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  lfs: true
  clean: true
- bash: |
   sudo apt install -y openslide-tools python3 python3-openslide
   python3 deepzoom_tile.py test.svs
   mkdir static
   mv test_files static
   mv index.html static
   mv images static
   mv test.dzi static
  displayName: 'Extract svs'
  
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise(8b90224d-e668-44e0-966d-eaccab1d5e63)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch --account-name svsdemo --source static --destination ''$web'' --overwrite'
